apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
       app: elasticsearch
  replicas: 3
  template:
    metadata:
        labels:
          app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:6.8.8
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        - name: node.name
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: cluster.name
          value: fleetman-elk-cluster
        - name: discovery.zen.ping.unicast.hosts
          value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
        - name: discovery.zen.minimum_master_nodes
          value: "2"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m" 
        volumeMounts:
        - name: elk-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elk-data
          persistentVolumeClaim:
             claimName: elk-pvc
      initContainers:
      - name: data-path-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true 
        volumeMounts:
        - name: elk-data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elk-data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: elk-ssd
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: logstash
spec:
  selector:
    matchLabels:
       app: logstash
  replicas:
  template:
      metadata:
         labels:
            app: logstash 
      spec:
         containers:
         - name: logstash
           image: logstash:6.8.8
           volumeMounts:
             - name: logstash-log
               mountPath: /var/log/logstash
           env:
           - name: SPRING_PROFILES_ACTIVE
             value: production-microservice
         volumes:
           - name: logstash-log
             persistentVolumeClaim:
                claimName: logstash-pvc    

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
spec:
  storageClassName: logstash-ssd
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: elk-ssd
provisioner: kubernetes.io/gce-pd
parameters:
   type: pd-standard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: logstash-ssd
provisioner: kubernetes.io/gce-pd
parameters:
   type: pd-standard
