apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
    - name: queue 
      port: 8161
      nodePort: 30010
    - name: msgs
      port: 61616
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-database
spec:
  selector:
    app: database 
  ports:
    - name: database
      port: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker 
  ports:
    - name: position-tracker
      port: 8080
  type: ClusterIP 
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: http
      port: 27017 
  type: ClusterIP
