apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
       app: queue
  replicas: 1
  template:
    metadata:
        labels:
          app: queue 
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
       app: database
  replicas: 1
  template:
    metadata:
        labels:
          app: database
    spec:
      containers:
      - name: queue
        image: mysql:5
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: password
         - name: MYSQL_DATABASE
           value: fleetman
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
       app: position-simulator
  replicas: 1
  template:
    metadata:
        labels:
          app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image:  richardchesterwood/k8s-fleetman-position-simulator:release2
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
       app: position-tracker
  replicas: 1
  template:
    metadata:
        labels:
          app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image:  richardchesterwood/k8s-fleetman-position-tracker:release3
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway 
spec:
  selector:
    matchLabels:
       app: api-gateway
  replicas: 1
  template:
    metadata:
        labels:
          app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image:  richardchesterwood/k8s-fleetman-api-gateway:release2
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
       app: webapp
  replicas: 1
  template:
    metadata:
        labels:
          app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb
spec:
  selector:
    matchLabels:
       app: mongodb
  replicas:
  template:
      metadata:
         labels:
            app: mongodb
      spec:
         containers:
         - name: mongodb
           image: mongo:3.6.5-jessie
           volumeMounts:
             - name: mongo-db-path
               mountPath: /data/db
           env:
           - name: SPRING_PROFILES_ACTIVE
             value: production-microservice
         volumes:
           - name: mongo-db-path
             persistentVolumeClaim: 
                claimName: mongo-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mongo-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 20Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
   name: mongo-ssd
provisioner: kubernetes.io/gce-pd
parameters:
   type: pd-standard
